import Vue from 'vue';
import draggable from 'vuedraggable';
import Input from './Input.vue';
import InputSelect from './InputSelect.vue';
import ButtonWrap from './ButtonWrap.vue';
import BackNav from './BackNav.vue';
import BottomNav from './BottomNav.vue';
import DefaultFilterWrap from './DefaultFilterWrap.vue';
import VCCalendar from './VC-Calendar.vue';
import VCCalendarSelect from './VC-CalendarSelect.vue';
import LoadingOverlay from './Loading-Overlay.vue';
import ModalDialog from './Modal-Dialog.vue';
import Select from './Select.vue';
import Checkbox from './Checkbox.vue';
import CheckboxFull from './CheckboxFull.vue';
import ButtonCheck from './ButtonCheck.vue';
import Loading from './Loading.vue';
import LoaderLay from './LoaderLay.vue';
import MainBlock from './MainBlock.vue';
import HomeHeader from './HomeHeader.vue';
import SettingsButton from './SettingsButton.vue';
import LogoutModal from './LogoutModal.vue';
import StatusModal from './StatusModal.vue';
import EditHolidayModal from './EditHolidayModal.vue';
import SelectCustomerModal from './SelectCustomerModal.vue';

Vue.component('C-Input', Input);
Vue.component('C-Input-Select', InputSelect);
Vue.component('C-Button-Wrap', ButtonWrap);
Vue.component('C-Back-Nav', BackNav);
Vue.component('C-Bottom-Nav', BottomNav);
Vue.component('C-vc-calendar', VCCalendar);
Vue.component('C-vc-calendar-select', VCCalendarSelect);
Vue.component('C-Loading-Overlay', LoadingOverlay);
Vue.component('C-Loading', Loading);
Vue.component('C-LoaderLay', LoaderLay);
Vue.component('C-Modal-Dialog', ModalDialog);
Vue.component('C-Draggable', draggable);
Vue.component('C-Select', Select);
Vue.component('C-Checkbox', Checkbox);
Vue.component('C-Checkbox-Full', CheckboxFull);
Vue.component('C-Button-Check', ButtonCheck);
Vue.component('C-Filter-Wrap', DefaultFilterWrap);
Vue.component('C-Main-Block', MainBlock);
Vue.component('C-Home-Header', HomeHeader);
Vue.component('C-Settings-Button', SettingsButton);
Vue.component('C-Logout-Modal', LogoutModal);
Vue.component('C-Status-Modal', StatusModal);
Vue.component('C-edit-holiday-dialog', EditHolidayModal);
Vue.component('C-select-customer-modal', SelectCustomerModal);
